### ISSUE TITLE
RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 20 but got size 21 for tensor number 1 in the list.

### ISSUE THREAD

**Issue by vedantroy** [lucidrains/imagen-pytorch#106]
The following code breaks:

```python3
    batch = next(train_dl_iter)
    print(batch['img'].shape, batch["caption"])
    print(len(batch["caption"][0]))
    trainer(
        images=batch['img'],
        texts = batch["caption"],
        unet_number = 1,
        max_batch_size= BATCH_SIZE,
    )
    trainer.train_step(unet_number=1)
```

To give some details:
- `batch['img']` is a tensor of shape `(1, 3, 800, 600)`
- `batch['caption']` is a Python list with a single string of length 271
- `BATCH_SIZE` is 1

```
Traceback (most recent call last):
  File "/home/vedant/Desktop/ml-experiments/imagen/train.py", line 34, in <module>
    trainer(
  File "/home/vedant/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/vedant/.local/lib/python3.10/site-packages/imagen_pytorch/trainer.py", line 99, in inner
    out = fn(model, *args, **kwargs)
  File "/home/vedant/.local/lib/python3.10/site-packages/imagen_pytorch/trainer.py", line 566, in forward
    loss = self.imagen(*chunked_args, unet_number = unet_number, **chunked_kwargs)
  File "/home/vedant/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/vedant/.local/lib/python3.10/site-packages/imagen_pytorch/imagen_pytorch.py", line 2114, in forward
    return self.p_losses(unet, images, times, text_embeds = text_embeds, text_mask = text_masks, cond_images = cond_images, noise_scheduler = noise_scheduler, lowres_cond_img = lowres_cond_img, lowres_aug_times = lowres_aug_times, pred_objective = pred_objective, p2_loss_weight_gamma = p2_loss_weight_gamma)
  File "/home/vedant/.local/lib/python3.10/site-packages/imagen_pytorch/imagen_pytorch.py", line 2026, in p_losses
    pred = unet.forward(
  File "/home/vedant/.local/lib/python3.10/site-packages/imagen_pytorch/imagen_pytorch.py", line 1570, in forward
    x = add_skip_connection(x)
  File "/home/vedant/.local/lib/python3.10/site-packages/imagen_pytorch/imagen_pytorch.py", line 1567, in <lambda>
    add_skip_connection = lambda x: torch.cat((x, hiddens.pop() * self.skip_connect_scale), dim = 1)
RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 20 but got size 21 for tensor number 1 in the list.
```

The setup code is:
```python3
# text => img UNet
unet1 = BaseUnet64(
    dim=256,
)

imagen = Imagen(
    unets=(unet1,),
    image_sizes=(64,),
    auto_normalize_img=True,
).cuda()

# custom dataset I made
ds = ImageCaptionDataset()

BATCH_SIZE = 1
train_dl = DataLoader(ds, batch_size=BATCH_SIZE, shuffle=True, pin_memory=True)
train_dl_iter = iter(train_dl)
trainer = ImagenTrainer(imagen)
```

I'm guessing this is an issue with something in the UNet, at the same time, I have to imagine the bug is on my end.
But, I'm not doing anything fancy, so I'm not sure what's up.

Will investigate further.

**Comment by lucidrains** [comment]
@vedantroy oh, the images being passed in must be squares (i've added a more informative error message in the latest commit https://github.com/lucidrains/imagen-pytorch/commit/2191261fac59957448b395d5bb0f1cf199e68823)
