### ISSUE TITLE
TypeError: __init__() got multiple values for argument 'self'

### ISSUE THREAD

**Issue by zzw-zwzhang** [lucidrains/imagen-pytorch#15]
```
Traceback (most recent call last):
  File "/import/home/w/.pycharm_helpers/pydev/pydevd.py", line 1483, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/import/home/w/.pycharm_helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/import/home/w/diffusion/imagen-pytorch/example_1.py", line 35, in <module>
    cond_drop_prob=0.5
  File "/import/home/w/diffusion/imagen-pytorch/imagen_pytorch/imagen_pytorch.py", line 1249, in __init__
    channels_out=unet_channels_out
  File "/import/home/w/diffusion/imagen-pytorch/imagen_pytorch/imagen_pytorch.py", line 998, in cast_model_parameters
    return self.__class__(**{**self._locals, **updated_kwargs})
TypeError: __init__() got multiple values for argument 'self'
```

In the debug mode, there is an error.

**Comment by lucidrains** [comment]
@zzw-zwzhang could you paste the script you are using that leads to the error?

**Comment by zzw-zwzhang** [comment]
```
import os
import torch
from imagen_pytorch import Unet, Imagen, SRUnet256

import matplotlib.pyplot as plt

os.environ["CUDA_VISIBLE_DEVICES"] = "0"


# unet for imagen
unet1 = Unet(
    dim=32,
    cond_dim=512,
    dim_mults=(1, 2, 4),
    num_resnet_blocks=3,
    layer_attns=(False, True, True),
    layer_cross_attns=(False, True, True)
)

unet2 = SRUnet256(
    dim=32,
    cond_dim=512,
    dim_mults=(1, 2, 4),
    num_resnet_blocks=(2, 4, 8),
    layer_attns=(False, False, True),
    layer_cross_attns=(False, False, True)
)

# imagen, which contains the unets above (base unet and super resoluting ones)
imagen = Imagen(
    unets=(unet1, unet2),
    image_sizes=(64, 256),
    beta_schedules=('cosine', 'linear'),
    timesteps=1000,
    cond_drop_prob=0.5
).cuda()

# mock images (get a lot of this) and text encodings from large T5
text_embeds = torch.randn(4, 256, 768).cuda()
text_masks = torch.ones(4, 256).bool().cuda()
images = torch.randn(4, 3, 256, 256).cuda()

# feed images into imagen, training each unet in the cascade
loss = imagen(images, text_embeds=text_embeds, text_masks=text_masks, unet_number=1)
loss.backward()

# do the above for many many many many steps
# now you can sample an image based on the text embeddings from the cascading ddpm
images = imagen.sample(texts=[
    'a whale breaching from afar',
    'young girl blowing out candles on her birthday cake',
    'fireworks with blue and green sparkles'
], cond_scale=2.)

print(images.shape)   # (3, 3, 256, 256)
fig = plt.figure()
plt.imshow(images[0, :].detach().cpu().numpy().transpose(1, 2, 0))
plt.show()
plt.close()
```

**Comment by lucidrains** [comment]
@zzw-zwzhang oh weird, it runs for me. which version of the library are you on?

**Comment by zzw-zwzhang** [comment]
version = '0.0.47'
