### ISSUE TITLE
"AttributeError: 'GradientState' object has no attribute '_iterate_samples_seen'" on trainer.train_step()

### ISSUE THREAD

**Issue by Syntaxxor** [lucidrains/imagen-pytorch#178]
I'm attempting to train my own model on this on my own machine. But on both my Windows machine and Google Colab, when I try to use `train_step()`, it returns the error above. My code is directly based on the tutorial in the Dataloader section.

The following is the full text of the error:
```Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\site-packages\accelerate\data_loader.py", line 348, in __iter__
    current_batch = next(dataloader_iter)
  File "C:\Program Files\Python310\lib\site-packages\torch\utils\data\dataloader.py", line 681, in __next__
    data = self._next_data()
  File "C:\Program Files\Python310\lib\site-packages\torch\utils\data\dataloader.py", line 720, in _next_data
    index = self._next_index()  # may raise StopIteration
  File "C:\Program Files\Python310\lib\site-packages\torch\utils\data\dataloader.py", line 671, in _next_index
    return next(self._sampler_iter)  # may raise StopIteration
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\dev\imagen-test\imagen-train.py", line 54, in <module>
    main()
  File "C:\dev\imagen-test\imagen-train.py", line 46, in main
    loss = trainer.train_step(unet_number = 1, max_batch_size = 4)
  File "C:\Program Files\Python310\lib\site-packages\imagen_pytorch\trainer.py", line 562, in train_step
    loss = self.step_with_dl_iter(self.train_dl_iter, unet_number = unet_number, **kwargs)
  File "C:\Program Files\Python310\lib\site-packages\imagen_pytorch\trainer.py", line 578, in step_with_dl_iter
    dl_tuple_output = cast_tuple(next(dl_iter))
  File "C:\Program Files\Python310\lib\site-packages\imagen_pytorch\data.py", line 18, in cycle
    for data in dl:
  File "C:\Program Files\Python310\lib\site-packages\accelerate\data_loader.py", line 350, in __iter__
    self.gradient_state._iterate_samples_seen(find_batch_size(current_batch))
AttributeError: 'GradientState' object has no attribute '_iterate_samples_seen'
```

It almost looks like this could be a torch/accelerate error, or maybe imagen-pytorch wants an earlier version? I'm not entirely sure. But I'd appreciate any help.

**Comment by Syntaxxor** [comment]
It turned out that for whatever reason, it wasn't loading the images. The issue is resolved now. Ignore this issue.
