### ISSUE TITLE
ValueError: unknown imagen type None

### ISSUE THREAD

**Issue by wasyleque** [lucidrains/imagen-pytorch#196]
Hi
I tried to do some testing with model downloaded from huggingface [https://huggingface.co/Cene655/Imagen-pytorch/tree/main](url)
But after runing `imagen --model ./imagen-pytorch.pt "A cute puppy"
`
I got an error 
`loading Imagen from /home/piotr/Documents/imagen-pytorch.pt, saved at version None - current package version is 1.9.4
Traceback (most recent call last):
  File "/home/piotr/anaconda3/bin/imagen", line 33, in <module>
    sys.exit(load_entry_point('imagen-pytorch==1.10.1', 'console_scripts', 'imagen')())
  File "/home/piotr/anaconda3/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/piotr/anaconda3/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/piotr/anaconda3/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/piotr/anaconda3/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/piotr/anaconda3/lib/python3.9/site-packages/imagen_pytorch/cli.py", line 41, in imagen
    imagen = load_imagen_from_checkpoint(str(model_path), load_ema_if_available = load_ema)
  File "/home/piotr/anaconda3/lib/python3.9/site-packages/imagen_pytorch/utils.py", line 33, in load_imagen_from_checkpoint
    raise ValueError(f'unknown imagen type {imagen_type}')
ValueError: unknown imagen type None
`

**Comment by lucidrains** [comment]
oh that is a different repository that is incomplete, and also went closed source
