### ISSUE TITLE
RuntimeError: "normal_kernel_cuda" not implemented for 'Int'

### ISSUE THREAD

**Issue by daniellochner** [lucidrains/imagen-pytorch#199]
Hi there,

I'm trying to use imagen-pytorch (1.11.0) on my university's a100 GPU cluster. They have **Python 3.9.5** installed.

I'm encountering the following error though:
> Traceback (most recent call last):
  File "/home/lchdan004/terrain-ml/src/terrain_ml.py", line 148, in <module>
    main()
  File "/home/lchdan004/terrain-ml/src/terrain_ml.py", line 143, in main
    train(args)
  File "/home/lchdan004/terrain-ml/src/terrain_ml.py", line 67, in train
    train_loss += trainer.train_step(unet_number=1, max_batch_size=args.batch_size)
  File "/home/lchdan004/terrain-ml/venv/lib/python3.9/site-packages/imagen_pytorch/trainer.py", line 590, in train_step
    loss = self.step_with_dl_iter(self.train_dl_iter, unet_number = unet_number, **kwargs)
  File "/home/lchdan004/terrain-ml/venv/lib/python3.9/site-packages/imagen_pytorch/trainer.py", line 608, in step_with_dl_iter
    loss = self.forward(**{**kwargs, **model_input})
  File "/home/lchdan004/terrain-ml/venv/lib/python3.9/site-packages/imagen_pytorch/trainer.py", line 135, in inner
    out = fn(model, *args, **kwargs)
  File "/home/lchdan004/terrain-ml/venv/lib/python3.9/site-packages/imagen_pytorch/trainer.py", line 958, in forward
    loss = self.imagen(*chunked_args, unet = self.unet_being_trained, unet_number = unet_number, **chunked_kwargs)
  File "/home/lchdan004/terrain-ml/venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/lchdan004/terrain-ml/venv/lib/python3.9/site-packages/imagen_pytorch/imagen_pytorch.py", line 2465, in forward
    return self.p_losses(unet, images, times, text_embeds = text_embeds, text_mask = text_masks, cond_images = cond_images, noise_scheduler = noise_scheduler, lowres_cond_img = lowres_cond_img, lowres_aug_times = lowres_aug_times, pred_objective = pred_objective, p2_loss_weight_gamma = p2_loss_weight_gamma, random_crop_size = random_crop_size)
  File "/home/lchdan004/terrain-ml/venv/lib/python3.9/site-packages/imagen_pytorch/imagen_pytorch.py", line 2299, in p_losses
    noise = default(noise, lambda: torch.randn_like(x_start))
  File "/home/lchdan004/terrain-ml/venv/lib/python3.9/site-packages/imagen_pytorch/imagen_pytorch.py", line 66, in default
    return d() if callable(d) else d
  File "/home/lchdan004/terrain-ml/venv/lib/python3.9/site-packages/imagen_pytorch/imagen_pytorch.py", line 2299, in <lambda>
    noise = default(noise, lambda: torch.randn_like(x_start))
RuntimeError: "normal_kernel_cuda" not implemented for 'Int'

**Comment by lucidrains** [comment]
@daniellochner Hi Daniel

It most likely means you are passing in integers (perhaps the images with values ranging from 0 to 255) rather than floats (ranging from 0. to 1.)

**Comment by daniellochner** [comment]
Ah thanks so much Phil, all working as expected now! Appreciate the little assertion you added to 1.11.1 as well haha! ;)

**Comment by lucidrains** [comment]
@daniellochner nice! glad it is working :D
