### ISSUE TITLE
@Beartype caused an error

### ISSUE THREAD

**Issue by xiaolxl** [lucidrains/imagen-pytorch#283]
After I use pip install imagen pytoch to install, I run the imagen config command, and the following error is reported

Traceback (most recent call last):
  File "/root/miniconda3/bin/imagen", line 5, in <module>
    from imagen_pytorch.cli import imagen
  File "/root/miniconda3/lib/python3.8/site-packages/imagen_pytorch/__init__.py", line 1, in <module>
    from imagen_pytorch.imagen_pytorch import Imagen, Unet
  File "/root/miniconda3/lib/python3.8/site-packages/imagen_pytorch/imagen_pytorch.py", line 1752, in <module>
    class Imagen(nn.Module):
  File "/root/miniconda3/lib/python3.8/site-packages/beartype/_decor/cache/cachedecor.py", line 77, in beartype
    return beartype_args_mandatory(obj, conf)
  File "/root/miniconda3/lib/python3.8/site-packages/beartype/_decor/_core.py", line 123, in beartype_args_mandatory
    return _beartype_type(cls=obj, conf=conf)  # type: ignore[return-value]
  File "/root/miniconda3/lib/python3.8/site-packages/beartype/_decor/_core.py", line 312, in _beartype_type
    raise BeartypeDecorWrappeeException(
beartype.roar.BeartypeDecorWrappeeException: <class 'imagen_pytorch.imagen_pytorch.Imagen'> not decoratable by @beartype, as non-dataclasses (i.e., types not decorated by @dataclasses.dataclass) currently unsupported by @beartype

**Comment by xiaolxl** [comment]
> @xiaolxl darn
> 
> would you like to try [8243df6](https://github.com/lucidrains/imagen-pytorch/commit/8243df6c8c49a1ba605bd8d8b3d65fa939dc898b)
> 
> in the worst case, i'll just remove it

Thank you very much. I can use it normally, but I hope it can also be updated on the pip
