### ISSUE TITLE
Inpainting doesn't work due to error with `inpaint_masks` shape

### ISSUE THREAD

**Issue by jameshball** [lucidrains/imagen-pytorch#292]
Hi! I am having a small issue with inpainting:

I'm running this on a pre-trained model:
```python
patch = trainer.sample(
    batch_size=1,
    text_embeds=conds,
    inpaint_images=inpaint_patch.unsqueeze(0),
    inpaint_masks=inpaint_mask.unsqueeze(0),
    inpaint_resample_times=1,
)
```

and the shapes of the fields are as follows:

```python
text_embeds.shape = (1, 1, 3)    # NB: Hackily conditioning on this not using text embeddings, but custom conditions
inpaint_images.shape = (1, 3, 64, 64)
inpaint_masks.shape = (1, 3, 64, 64)
```

When this runs I get this error:

```
Traceback (most recent call last):
  File "C:\dev\kidney-diffusion\outpainting.py", line 75, in <module>
    main()
  File "C:\dev\kidney-diffusion\outpainting.py", line 44, in main
    patch = trainer.sample(
  File "C:\dev\kidney-diffusion\venv\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "C:\dev\kidney-diffusion\venv\lib\site-packages\imagen_pytorch\trainer.py", line 135, in inner
    out = fn(model, *args, **kwargs)
  File "C:\dev\kidney-diffusion\venv\lib\site-packages\imagen_pytorch\trainer.py", line 195, in inner
    return fn(self, *args, **kwargs)
  File "C:\dev\kidney-diffusion\venv\lib\site-packages\imagen_pytorch\trainer.py", line 950, in sample
    output = self.imagen.sample(*args, device = self.device, **kwargs)
  File "C:\dev\kidney-diffusion\venv\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "C:\dev\kidney-diffusion\venv\lib\site-packages\imagen_pytorch\imagen_pytorch.py", line 100, in inner
    out = fn(model, *args, **kwargs)
  File "<@beartype(imagen_pytorch.imagen_pytorch.Imagen.sample) at 0x1d00f1f69d0>", line 40, in sample
  File "C:\dev\kidney-diffusion\venv\lib\site-packages\imagen_pytorch\imagen_pytorch.py", line 2290, in sample
    img = self.p_sample_loop(
  File "C:\dev\kidney-diffusion\venv\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "C:\dev\kidney-diffusion\imagen_pytorch.py", line 2131, in p_sample_loop
    img, x_start = self.p_sample(
  File "C:\dev\kidney-diffusion\venv\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "C:\dev\kidney-diffusion\venv\lib\site-packages\imagen_pytorch\imagen_pytorch.py", line 2056, in p_sample
    (model_mean, _, model_log_variance), x_start = self.p_mean_variance(unet, x = x, t = t, t_next = t_next, noise_scheduler = noise_scheduler, text_embeds = text_embeds, text_mask = text_mask, cond_images = cond_images, cond_scale = cond_scale, lowres_cond_img = lowres_cond_img, self_cond = self_cond, lowres_noise_times = lowres_noise_times, pred_objective = pred_objective, dynamic_threshold = dynamic_threshold)
  File "C:\dev\kidney-diffusion\venv\lib\site-packages\imagen_pytorch\imagen_pytorch.py", line 2007, in p_mean_variance
    pred = default(model_output, lambda: unet.forward_with_cond_scale(x, noise_scheduler.get_condition(t), text_embeds = text_embeds, text_mask = text_mask, cond_images = cond_images, cond_scale = cond_scale, lowres_cond_img = lowres_cond_img, self_cond = self_cond, lowres_noise_times = self.lowres_noise_schedule.get_condition(lowres_noise_times)))
  File "C:\dev\kidney-diffusion\venv\lib\site-packages\imagen_pytorch\imagen_pytorch.py", line 67, in default
    return d() if callable(d) else d
  File "C:\dev\kidney-diffusion\venv\lib\site-packages\imagen_pytorch\imagen_pytorch.py", line 2007, in <lambda>
    pred = default(model_output, lambda: unet.forward_with_cond_scale(x, noise_scheduler.get_condition(t), text_embeds = text_embeds, text_mask = text_mask, cond_images = cond_images, cond_scale = cond_scale, lowres_cond_img = lowres_cond_img, self_cond = self_cond, lowres_noise_times = self.lowres_noise_schedule.get_condition(lowres_noise_times)))
  File "C:\dev\kidney-diffusion\venv\lib\site-packages\imagen_pytorch\imagen_pytorch.py", line 1480, in forward_with_cond_scale
    logits = self.forward(*args, **kwargs)
  File "C:\dev\kidney-diffusion\venv\lib\site-packages\imagen_pytorch\imagen_pytorch.py", line 1528, in forward
    x = self.init_conv(x)
  File "C:\dev\kidney-diffusion\venv\lib\site-packages\torch\nn\modules\module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\dev\kidney-diffusion\venv\lib\site-packages\imagen_pytorch\imagen_pytorch.py", line 1040, in forward
    fmaps = tuple(map(lambda conv: conv(x), self.convs))
  File "C:\dev\kidney-diffusion\venv\lib\site-packages\imagen_pytorch\imagen_pytorch.py", line 1040, in <lambda>
    fmaps = tuple(map(lambda conv: conv(x), self.convs))
  File "C:\dev\kidney-diffusion\venv\lib\site-packages\torch\nn\modules\module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\dev\kidney-diffusion\venv\lib\site-packages\torch\nn\modules\conv.py", line 463, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "C:\dev\kidney-diffusion\venv\lib\site-packages\torch\nn\modules\conv.py", line 459, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Expected 3D (unbatched) or 4D (batched) input to conv2d, but got input of size: [1, 1, 3, 64, 64]
```

This is due to the singleton dimension that's added to `inpaint_masks` with `rearrange` here: https://github.com/lucidrains/imagen-pytorch/blob/main/imagen_pytorch/imagen_pytorch.py#L2108

I inherited `Imagen` and overrode `p_sample_loop` and removed the `rearrange` call, replacing the line with:

```python
inpaint_masks = self.resize_to(inpaint_masks, shape[-1]).bool()
```

and it seems to work fine afterwards.

Is this `rearrange` intentionally there or is the shape of my masks incorrect?

**Comment by lucidrains** [comment]
the mask should be of shape (batch, height, width)

**Comment by jameshball** [comment]
🤦‍♂️ of course - that makes sense. Thank you
