### ISSUE TITLE
forward() does not support the video frames arguments

### ISSUE THREAD

**Issue by youbin2014** [lucidrains/imagen-pytorch#311]
C:\ProgramData\Anaconda3\envs\Imagen\python.exe C:/Users/User/PycharmProjects/imagen-pytorch/test.py
The base dimension of your u-net should ideally be no smaller than 128, as recommended by a professional DDPM trainer https://nonint.com/2022/05/04/friends-dont-let-friends-train-small-diffusion-models/
0it [00:00, ?it/s]
sampling loop time step:   0%|          | 0/1000 [00:00<?, ?it/s]
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "C:/Users/User/PycharmProjects/imagen-pytorch/test.py", line 47, in <module>
    images = imagen.sample(texts = [
  File "C:\ProgramData\Anaconda3\envs\Imagen\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\User\PycharmProjects\imagen-pytorch\imagen_pytorch\imagen_pytorch.py", line 100, in inner
    out = fn(model, *args, **kwargs)
  File "<@beartype(imagen_pytorch.imagen_pytorch.Imagen.sample) at 0x1d012786820>", line 42, in sample
  File "C:\Users\User\PycharmProjects\imagen-pytorch\imagen_pytorch\imagen_pytorch.py", line 2382, in sample
    img = self.p_sample_loop(
  File "C:\ProgramData\Anaconda3\envs\Imagen\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\User\PycharmProjects\imagen-pytorch\imagen_pytorch\imagen_pytorch.py", line 2214, in p_sample_loop
    img, x_start = self.p_sample(
  File "C:\ProgramData\Anaconda3\envs\Imagen\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\User\PycharmProjects\imagen-pytorch\imagen_pytorch\imagen_pytorch.py", line 2113, in p_sample
    (model_mean, _, model_log_variance), x_start = self.p_mean_variance(
  File "C:\Users\User\PycharmProjects\imagen-pytorch\imagen_pytorch\imagen_pytorch.py", line 2049, in p_mean_variance
    pred = default(model_output, lambda: unet.forward_with_cond_scale(
  File "C:\Users\User\PycharmProjects\imagen-pytorch\imagen_pytorch\imagen_pytorch.py", line 70, in default
    return d() if callable(d) else d
  File "C:\Users\User\PycharmProjects\imagen-pytorch\imagen_pytorch\imagen_pytorch.py", line 2049, in <lambda>
    pred = default(model_output, lambda: unet.forward_with_cond_scale(
  File "C:\Users\User\PycharmProjects\imagen-pytorch\imagen_pytorch\imagen_pytorch.py", line 1506, in forward_with_cond_scale
    logits = self.forward(*args, **kwargs)
TypeError: forward() got an unexpected keyword argument 'cond_video_frames'

Process finished with exit code 1

**Comment by youbin2014** [comment]
fixed by adding two arguments in forward()

    def forward(
        self,
        x,
        time,
        *,
        lowres_cond_img = None,
        lowres_noise_times = None,
        text_embeds = None,
        text_mask = None,
        cond_images = None,
        self_cond = None,
        cond_drop_prob = 0.,
        cond_video_frames = None, # added this
        post_cond_video_frames = None, # added this

    ):
        batch_size, device = x.shape[0], x.device

**Comment by lucidrains** [comment]
@youbin2014 oh hey Hanbin, could you show me your full script? the video frames conditioning should only be available on the 3d unets (you need to be training on video too)

**Comment by lucidrains** [comment]
@youbin2014 oh, this is my bad :pray: 

can you let me know if the [latest version](https://github.com/lucidrains/imagen-pytorch/commit/18da6654d38ba18bc4d9afcc0735be21949fcf64) fixes this?

**Comment by youbin2014** [comment]
@lucidrains Hi, the latest version fixes it. Thanks!

**Comment by lucidrains** [comment]
@youbin2014 woohoo! thanks for raising the issue!
