### ISSUE TITLE
Torch object has no attribute pi, simple find and replace fixes it

### ISSUE THREAD

**Issue by NelBlue** [lucidrains/imagen-pytorch#38]
```
>>> import imagen_pytorch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "~/repos/MeshGen/lucidrains_imagen/imagen-pytorch/imagen_pytorch/__init__.py", line 1, in <module>
    from imagen_pytorch.imagen_pytorch import Imagen, Unet
  File "~/repos/MeshGen/lucidrains_imagen/imagen-pytorch/imagen_pytorch/imagen_pytorch.py", line 293, in <module>
    def alpha_cosine_log_snr(t, s: float = 0.008):
  File "~/.local/lib/python3.8/site-packages/torch/jit/_script.py", line 1143, in script
    fn = torch._C._jit_script_compile(
RuntimeError: 
object has no attribute pi:
  File "~/repos/MeshGen/lucidrains_imagen/imagen-pytorch/imagen_pytorch/imagen_pytorch.py", line 294
@torch.jit.script
def alpha_cosine_log_snr(t, s: float = 0.008):
    return -log((torch.cos((t + s) / (1 + s) * torch.pi * 0.5) ** -2) - 1)
                                               ~~~~~~~~ <--- HERE
```
opening imagen_pytorch.py and doing a simple find and replace for torch.pi to math.pi fixed it on my end.

Hope it's not an internal issues on my end but figured I'd share

**Comment by lucidrains** [comment]
@NelBlue thanks for reporting this! https://github.com/lucidrains/imagen-pytorch/commit/f7bb107b417905c778215344e9c63eb4d1f4b6ac

**Comment by NelBlue** [comment]
Thanks again for all your hard work!
